# Generated by Django 4.1 on 2023-01-13 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(default=None, max_length=100, null=True)),
                ('etype', models.CharField(default=None, max_length=100, null=True)),
                ('industry', models.CharField(default=None, max_length=100, null=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('pincode', models.CharField(default=None, max_length=100, null=True)),
                ('executive', models.CharField(default=None, max_length=100, null=True)),
                ('phone', models.CharField(default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('profile', models.CharField(default=None, max_length=700, null=True)),
                ('logo', models.FileField(default=None, null=True, upload_to='main/static/logos/')),
            ],
            options={
                'db_table': 'employer',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('jobdesc', models.CharField(default=None, max_length=700, null=True)),
                ('vacno', models.IntegerField(default=None, null=True)),
                ('experience', models.CharField(default=None, max_length=100, null=True)),
                ('basicpay', models.CharField(default=None, max_length=100, null=True)),
                ('fnarea', models.CharField(default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('industry', models.CharField(default=None, max_length=200, null=True)),
                ('ugqual', models.CharField(default=None, max_length=100, null=True)),
                ('pgqual', models.CharField(default=None, max_length=100, null=True)),
                ('profile', models.CharField(default=None, max_length=700, null=True)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('eid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('experience', models.CharField(default=None, max_length=100, null=True)),
                ('skills', models.CharField(default=None, max_length=100, null=True)),
                ('basic_edu', models.CharField(default=None, max_length=100, null=True)),
                ('master_edu', models.CharField(default=None, max_length=100, null=True)),
                ('other_qual', models.CharField(default=None, max_length=100, null=True)),
                ('dob', models.CharField(default=None, max_length=50, null=True)),
                ('Resume', models.FileField(default=None, null=True, upload_to='main/static/resumes/')),
                ('photo', models.FileField(default=None, null=True, upload_to='main/static/photos/')),
            ],
            options={
                'db_table': 'jobseeker',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('user_type', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('sel_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('job_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'selection',
            },
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='log_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.login'),
        ),
        migrations.AddField(
            model_name='employer',
            name='log_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.login'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=None, null=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('job_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'application',
            },
        ),
    ]
