# Generated by Django 4.2.3 on 2024-03-06 04:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=750)),
            ],
            options={
                'db_table': 'allskills',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('screening_answer_one', models.TextField(default=None, null=True)),
                ('screening_answer_two', models.TextField(default=None, null=True)),
                ('status', models.IntegerField(default=None, null=True)),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('why_desc', models.CharField(blank=True, default=None, max_length=700, null=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('institution_type', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(default=None, max_length=100, null=True)),
                ('etype', models.CharField(default=None, max_length=100, null=True)),
                ('industry', models.CharField(default=None, max_length=100, null=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('pincode', models.CharField(default=None, max_length=100, null=True)),
                ('executive', models.CharField(default=None, max_length=100, null=True)),
                ('phone', models.CharField(default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('profile', models.CharField(default=None, max_length=700, null=True)),
                ('strength', models.CharField(default=None, max_length=200, null=True)),
                ('turnover', models.CharField(default=None, max_length=300, null=True)),
                ('details', models.CharField(default=None, max_length=700, null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='logos/')),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('yearfounded', models.CharField(default=None, max_length=10, null=True)),
                ('size', models.CharField(default=None, max_length=20, null=True)),
                ('city', models.CharField(default=None, max_length=30, null=True)),
                ('fblink', models.CharField(default=None, max_length=100, null=True)),
                ('twlink', models.CharField(default=None, max_length=100, null=True)),
                ('inlink', models.CharField(default=None, max_length=100, null=True)),
                ('lnlink', models.CharField(default=None, max_length=100, null=True)),
                ('cover', models.ImageField(blank=True, default=None, null=True, upload_to='cover/')),
                ('about', models.CharField(default='Not Specified', max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'employer',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('jobdesc', models.CharField(default=None, max_length=700, null=True)),
                ('vacno', models.IntegerField(default=None, null=True)),
                ('experience', models.CharField(default=None, max_length=100, null=True)),
                ('basicpay', models.CharField(default=None, max_length=50, null=True)),
                ('fnarea', models.CharField(default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('industry', models.CharField(default=None, max_length=200, null=True)),
                ('ugqual', models.CharField(default=None, max_length=100, null=True)),
                ('pgqual', models.CharField(default=None, max_length=100, null=True)),
                ('profile', models.CharField(default=None, max_length=700, null=True)),
                ('postdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobtype', models.CharField(default='Full Time', max_length=50)),
                ('skills', models.CharField(default=None, max_length=700, null=True)),
                ('notice_period', models.CharField(default=None, max_length=50, null=True)),
                ('responsibilities', models.CharField(default=None, max_length=700, null=True)),
                ('requirements', models.CharField(default=None, max_length=700, null=True)),
                ('num_of_visits', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=3)),
                ('suggestions', models.CharField(default='[]', max_length=2000)),
                ('job_desc', models.FileField(default=None, null=True, upload_to='job_description/')),
                ('eid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('experience', models.CharField(default=None, max_length=100, null=True)),
                ('skills', models.CharField(default=None, max_length=100, null=True)),
                ('basic_edu', models.CharField(default=None, max_length=100, null=True)),
                ('master_edu', models.CharField(default=None, max_length=100, null=True)),
                ('other_qual', models.CharField(default=None, max_length=100, null=True)),
                ('cursal', models.FloatField(default=0)),
                ('expsal', models.FloatField(default=0)),
                ('dob', models.CharField(default=None, max_length=50, null=True)),
                ('Resume', models.FileField(default=None, null=True, upload_to='resumes/')),
                ('photo', models.ImageField(default=None, null=True, upload_to='photos/')),
                ('notice_period', models.CharField(default=None, max_length=50, null=True)),
                ('role', models.CharField(default=None, max_length=750, null=True)),
            ],
            options={
                'db_table': 'jobseeker',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('user_type', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'mocktest',
            },
        ),
        migrations.CreateModel(
            name='MockTestInfo',
            fields=[
                ('testinfoid', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(default=None, max_length=100, null=True)),
                ('tech', models.CharField(default=None, max_length=100, null=True)),
                ('time_limit', models.IntegerField(default=0)),
                ('test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mocktest')),
            ],
            options={
                'db_table': 'mocktestinfo',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'newsletter',
            },
        ),
        migrations.CreateModel(
            name='RoleDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=750)),
            ],
            options={
                'db_table': 'roledetails',
            },
        ),
        migrations.CreateModel(
            name='Seminars',
            fields=[
                ('seminar_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=512)),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=512)),
                ('is_online', models.IntegerField(default=None, null=True)),
                ('web_link', models.CharField(max_length=200)),
                ('image', models.ImageField(default=None, null=True, upload_to='seminar/')),
                ('speaker', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'seminars',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=512)),
                ('step_description', models.CharField(max_length=512)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('step_resources', models.CharField(max_length=512)),
                ('step_tasks', models.CharField(max_length=512)),
                ('emp_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
            ],
            options={
                'db_table': 'steps',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100)),
                ('template_description', models.CharField(max_length=512)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('emp_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('testinfoid', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(default=None, max_length=100, null=True)),
                ('time_limit', models.IntegerField(default=0)),
                ('eid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.test')),
            ],
            options={
                'db_table': 'testinfo',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('organization', models.CharField(default=None, max_length=200, null=True)),
                ('time_period', models.CharField(default=None, max_length=50, null=True)),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'training',
            },
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_unread', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='main.login')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main.login')),
            ],
            options={
                'db_table': 'threads',
            },
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('testuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_ques', models.IntegerField(default=0)),
                ('answers', models.CharField(default=None, max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('apply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application')),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.test')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'testuser',
            },
        ),
        migrations.CreateModel(
            name='TestQues',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('ques_name', models.CharField(default=None, max_length=200, null=True)),
                ('option1', models.CharField(default=None, max_length=100, null=True)),
                ('option2', models.CharField(default=None, max_length=100, null=True)),
                ('option3', models.CharField(default=None, max_length=100, null=True)),
                ('option4', models.CharField(default=None, max_length=100, null=True)),
                ('correct', models.IntegerField()),
                ('images', models.ImageField(default=None, null=True, upload_to='test_images/')),
                ('testinfoid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testinfo')),
            ],
            options={
                'db_table': 'testques',
            },
        ),
        migrations.CreateModel(
            name='TemplateSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(default=None, null=True)),
                ('step_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.steps')),
                ('template_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.templates')),
            ],
            options={
                'db_table': 'templatesteps',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('sel_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=None, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('emp_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('job_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'selection',
            },
        ),
        migrations.CreateModel(
            name='ScreeningQuestions',
            fields=[
                ('screening_ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.TextField(default=None, null=True)),
                ('question_one', models.TextField(default=None, null=True)),
                ('question_two', models.TextField(default=None, null=True)),
                ('job_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
            ],
            options={
                'db_table': 'ScreeningQuestions',
            },
        ),
        migrations.CreateModel(
            name='ResumeFeedback',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
            ],
            options={
                'db_table': 'Resumefeedback',
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('any_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_score', models.CharField(default=None, max_length=10, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('no_of_pages', models.CharField(default=None, max_length=5, null=True)),
                ('predicted_field', models.CharField(default=None, max_length=100, null=True)),
                ('user_level', models.CharField(default=None, max_length=100, null=True)),
                ('actual_skills', models.CharField(default=None, max_length=500, null=True)),
                ('reco_skills', models.CharField(default=None, max_length=500, null=True)),
                ('reco_courses', models.CharField(default=None, max_length=1000, null=True)),
                ('recommendations', models.CharField(default=None, max_length=1000, null=True)),
                ('sparse_matrix_data', models.TextField(default=None, null=True)),
                ('jobseeker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'resumeanalysis',
            },
        ),
        migrations.CreateModel(
            name='ProfileVisits',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visiting_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(default=None, max_length=5, null=True)),
                ('e_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.employer')),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.jobseeker')),
            ],
            options={
                'db_table': 'profilevisits',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('notif_type', models.CharField(default=None, max_length=10, null=True)),
                ('readed', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_job', to='main.jobs')),
                ('rece_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_receiver', to='main.login')),
                ('send_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_sender', to='main.login')),
                ('testuser_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testuser')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='MockTestQues',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('ques_name', models.CharField(default=None, max_length=700, null=True)),
                ('option1', models.CharField(default=None, max_length=300, null=True)),
                ('option2', models.CharField(default=None, max_length=300, null=True)),
                ('option3', models.CharField(default=None, max_length=300, null=True)),
                ('option4', models.CharField(default=None, max_length=300, null=True)),
                ('correct', models.IntegerField()),
                ('images', models.ImageField(default=None, null=True, upload_to='test_images/')),
                ('body', models.TextField(default=None, null=True)),
                ('testinfoid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mocktestinfo')),
            ],
            options={
                'db_table': 'mocktestques',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('msg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.threads')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to='main.login')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to='main.login')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='LikedJobs',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('likedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'likedjobs',
            },
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='log_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.login'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('int_id', models.AutoField(primary_key=True, serialize=False)),
                ('int_link', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('schedule_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_done', models.BooleanField(default=False)),
                ('is_feedgiven', models.BooleanField(default=False)),
                ('cand_feedback', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('panel_req', models.IntegerField(default=0)),
                ('apply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application')),
                ('eid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('testuser_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testuser')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'interview',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_feedback', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('int_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.interview')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='ExperienceJob',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(default=None, max_length=100, null=True)),
                ('company', models.CharField(default=None, max_length=200, null=True)),
                ('time_period', models.CharField(default=None, max_length=50, null=True)),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('experience_month', models.IntegerField(null=True)),
                ('experience_year', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'experiencejob',
            },
        ),
        migrations.AddField(
            model_name='employer',
            name='log_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.login'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('edu_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100, null=True)),
                ('school', models.CharField(default=None, max_length=200, null=True)),
                ('time_period', models.CharField(default=None, max_length=50, null=True)),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='CandidateTemplateAssignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_step_order', models.IntegerField(default=None, null=True)),
                ('date_assigned', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application')),
                ('candidate_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
                ('template_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.templates')),
            ],
            options={
                'db_table': 'candidatetemplateassignments',
            },
        ),
        migrations.CreateModel(
            name='CandidateStepProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField()),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidatetemplateassignments')),
                ('step_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.steps')),
            ],
            options={
                'db_table': 'candidatestepprogress',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='eid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer'),
        ),
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobs'),
        ),
        migrations.AddField(
            model_name='application',
            name='screeningquestions_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.screeningquestions'),
        ),
        migrations.AddField(
            model_name='application',
            name='test',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testinfo'),
        ),
        migrations.AddField(
            model_name='application',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(default=None, max_length=100, null=True)),
                ('arole', models.CharField(default=None, max_length=100, null=True)),
                ('phone', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('log_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.login')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
