# Generated by Django 4.1 on 2023-01-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='main/static/photos/'),
        ),
    ]
