# Generated by Django 4.1 on 2023-01-13 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_employer_logo_alter_jobseeker_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='postdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='selection',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
