# Generated by Django 4.1 on 2023-01-17 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_jobseeker_about_jobseeker_title_experiencejob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisits',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visiting_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('e_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.employer')),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.jobseeker')),
            ],
            options={
                'db_table': 'profilevisits',
            },
        ),
    ]
