# Generated by Django 4.1 on 2023-01-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_threads_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.login'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.login'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.login'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.login'),
        ),
    ]
