# Generated by Django 4.1 on 2023-01-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_messages_receiver_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to='main.login'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to='main.login'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='main.login'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main.login'),
        ),
    ]
