# Generated by Django 4.1.4 on 2023-01-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_messages_receiver_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('any_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_score', models.CharField(default=None, max_length=10, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('no_of_pages', models.CharField(default=None, max_length=5, null=True)),
                ('predicted_field', models.CharField(default=None, max_length=100, null=True)),
                ('user_level', models.CharField(default=None, max_length=100, null=True)),
                ('actual_skills', models.CharField(default=None, max_length=500, null=True)),
                ('reco_skills', models.CharField(default=None, max_length=500, null=True)),
                ('reco_courses', models.CharField(default=None, max_length=1000, null=True)),
                ('recommendations', models.CharField(default=None, max_length=500, null=True)),
                ('jobseeker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'resumeanalysis',
            },
        ),
    ]
