# Generated by Django 4.1.4 on 2023-01-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_resumeanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='recommendations',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
