# Generated by Django 4.1.4 on 2023-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_resumeanalysis_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobtype',
            field=models.CharField(default='Full Time', max_length=50),
        ),
    ]
