# Generated by Django 4.1.4 on 2023-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_jobs_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='basicpay',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
