# Generated by Django 4.1.4 on 2023-01-28 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_jobs_basicpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedJobs',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('likedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'likedjobs',
            },
        ),
    ]
