# Generated by Django 4.1.4 on 2023-01-30 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_likedjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('notif_type', models.CharField(default=None, max_length=10, null=True)),
                ('rece_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_receiver', to='main.login')),
                ('send_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_sender', to='main.login')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
