# Generated by Django 4.1.4 on 2023-01-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_notifications_readed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='emp_id',
        ),
    ]
