# Generated by Django 4.1.4 on 2023-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_jobs_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='careerlevel',
            field=models.CharField(default='No experience', max_length=40, null=True),
        ),
    ]
