# Generated by Django 4.1.4 on 2023-02-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_jobs_careerlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='fblink',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='inlink',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='lnlink',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='size',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='twlink',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='yearfounded',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
