# Generated by Django 4.1.4 on 2023-02-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_employer_city_employer_fblink_employer_inlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logos/'),
        ),
    ]
