# Generated by Django 4.1.4 on 2023-02-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_employer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='cover/'),
        ),
    ]
