# Generated by Django 4.1.4 on 2023-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_employer_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
