# Generated by Django 4.1.4 on 2023-02-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_employer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_job', to='main.jobs'),
        ),
    ]
