# Generated by Django 4.1.4 on 2023-02-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_notifications_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilevisits',
            name='user_type',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
