# Generated by Django 4.1.4 on 2023-02-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_profilevisits_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='eid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer'),
        ),
    ]
