# Generated by Django 4.1.4 on 2023-02-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_threads_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='basicpay',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
