# Generated by Django 4.1.4 on 2023-02-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_jobs_basicpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='about',
            field=models.CharField(default='Not Specified', max_length=500, null=True),
        ),
    ]
