# Generated by Django 4.1.4 on 2023-02-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_employer_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='requirements',
            field=models.CharField(default=None, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='responsibilities',
            field=models.CharField(default=None, max_length=700, null=True),
        ),
    ]
