# Generated by Django 4.1.4 on 2023-02-20 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_jobs_requirements_jobs_responsibilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_limit', models.IntegerField(default=1)),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('ques_desc', models.CharField(default=None, max_length=500, null=True)),
                ('marks', models.IntegerField(default=1)),
                ('quiz_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_desc', models.CharField(default=None, max_length=300, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('ques_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
            ],
            options={
                'db_table': 'options',
            },
        ),
    ]
