# Generated by Django 4.1.4 on 2023-02-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_quiz_questions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='eid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer'),
        ),
    ]
