# Generated by Django 4.1.4 on 2023-02-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_quiz_eid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='ques_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='quiz_id',
        ),
    ]
