# Generated by Django 4.1.4 on 2023-02-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_options_ques_id_remove_questions_quiz_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
