# Generated by Django 4.1.4 on 2023-02-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_delete_options_delete_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='job_id',
        ),
    ]
