# Generated by Django 4.1.4 on 2023-02-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_quiz_eid_remove_quiz_job_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
