# Generated by Django 4.1.4 on 2023-02-20 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('testinfoid', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(default=None, max_length=100, null=True)),
                ('eid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.test')),
            ],
            options={
                'db_table': 'testinfo',
            },
        ),
        migrations.CreateModel(
            name='TestQues',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('ques_name', models.CharField(default=None, max_length=200, null=True)),
                ('option1', models.CharField(default=None, max_length=100, null=True)),
                ('option2', models.CharField(default=None, max_length=100, null=True)),
                ('option3', models.CharField(default=None, max_length=100, null=True)),
                ('option4', models.CharField(default=None, max_length=100, null=True)),
                ('correct', models.IntegerField()),
                ('testinfoid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testinfo')),
            ],
            options={
                'db_table': 'testques',
            },
        ),
    ]
