# Generated by Django 4.1.4 on 2023-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_test_testinfo_testques'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
    ]
