# Generated by Django 4.1.4 on 2023-02-20 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_testinfo_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('testuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answers', models.IntegerField()),
                ('total_ques', models.IntegerField()),
                ('answers', models.CharField(default=None, max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.test')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'testuser',
            },
        ),
    ]
