# Generated by Django 4.1.4 on 2023-02-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_testuser_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testinfo'),
        ),
    ]
