# Generated by Django 4.1.4 on 2023-02-22 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_application_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='testuser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testuser'),
        ),
    ]
