# Generated by Django 4.1.4 on 2023-02-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_notifications_testuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('int_id', models.AutoField(primary_key=True, serialize=False)),
                ('int_link', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('eid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobseeker')),
            ],
            options={
                'db_table': 'interview',
            },
        ),
    ]
