# Generated by Django 4.1.4 on 2023-02-27 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='schedule_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
