# Generated by Django 4.1.4 on 2023-03-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_interview_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='why_desc',
            field=models.CharField(blank=True, default=None, max_length=700, null=True),
        ),
    ]
