# Generated by Django 4.1.4 on 2023-03-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_application_why_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='c_feedback',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='e_feedback',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
