# Generated by Django 4.1.4 on 2023-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_interview_c_feedback_interview_e_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
