# Generated by Django 4.1.4 on 2023-03-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_interview_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='c_feedback',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='e_feedback',
        ),
    ]
