# Generated by Django 4.1.4 on 2023-03-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_remove_interview_c_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='cand_feedback',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_feedback', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('int_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.interview')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
