# Generated by Django 4.1.4 on 2023-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_interview_cand_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_feedgiven',
            field=models.BooleanField(default=False),
        ),
    ]
