# Generated by Django 4.1.4 on 2023-03-17 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='postdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
