# Generated by Django 4.1.4 on 2023-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_jobs_postdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'newsletter',
            },
        ),
    ]
