# Generated by Django 4.1.4 on 2023-03-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='num_of_visits',
            field=models.IntegerField(default=0),
        ),
    ]
