# Generated by Django 4.1.4 on 2023-03-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_jobs_num_of_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='testuser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testuser'),
        ),
    ]
