# Generated by Django 4.1.4 on 2023-03-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_interview_testuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=750)),
            ],
            options={
                'db_table': 'allskills',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('institution_type', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='RoleDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=750)),
            ],
            options={
                'db_table': 'roledetails',
            },
        ),
    ]
