# Generated by Django 4.1.5 on 2023-05-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_remove_jobs_careerlevel_jobs_notice_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='about',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='title',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='cursal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='expsal',
            field=models.IntegerField(default=0),
        ),
    ]
