# Generated by Django 4.1.5 on 2023-07-15 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_remove_jobseeker_about_remove_jobseeker_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(default=None, max_length=100, null=True)),
                ('arole', models.CharField(default=None, max_length=100, null=True)),
                ('phone', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('log_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.login')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
