# Generated by Django 4.2.3 on 2023-08-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0061_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="apply_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.application",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="panel_req",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobs", name="status", field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="jobs",
            name="suggestions",
            field=models.CharField(default="[]", max_length=2000),
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="notice_period",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="role",
            field=models.CharField(default=None, max_length=750, null=True),
        ),
        migrations.AddField(
            model_name="testuser",
            name="apply_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.application",
            ),
        ),
        migrations.AddField(
            model_name="testuser",
            name="emp_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.employer",
            ),
        ),
        migrations.CreateModel(
            name="ResumeFeedback",
            fields=[
                ("feed_id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "job_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.jobs",
                    ),
                ),
            ],
            options={"db_table": "Resumefeedback",},
        ),
    ]
