# Generated by Django 4.2.3 on 2023-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_feedback_rating_interview_apply_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testques',
            name='images',
            field=models.ImageField(default=None, null=True, upload_to='test_images/'),
        ),
    ]
