# Generated by Django 4.2.3 on 2023-10-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_testques_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_desc',
            field=models.FileField(default=None, null=True, upload_to='job_description/'),
        ),
    ]
