# Generated by Django 4.2.3 on 2024-02-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='cursal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='expsal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='details',
            field=models.CharField(default=None, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='strength',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='turnover',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='screeningquestions',
            name='questions',
            field=models.TextField(default=None, null=True),
        ),
    ]

