name: mpower

services:
  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mpower
      MYSQL_USER: user
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: password

    ports:
      - "3300:3306"
